function setup_paths()
% SETUP_PATHS Configures MATLAB search paths for the Retino-AI engine
% Project: SIH26038 - Explainable AI for Diabetic Retinopathy Screening in Rural India
%
% Usage:
%   setup_paths();

    matlabDir = fileparts(mfilename('fullpath'));
    aiEngineDir = fileparts(matlabDir);

    % Add MATLAB module subdirectories and submodules
    subdirs = { ...
        'data', ...
        fullfile('data', 'aptos'), ...
        fullfile('data', 'idrid'), ...
        fullfile('data', 'drive'), ...
        fullfile('data', 'messidor2'), ...
        'preprocessing', ...
        'quality_assessment', ...
        'feature_extraction', ...
        'models', ...
        fullfile('models', 'classification'), ...
        fullfile('models', 'vessel_segmentation'), ...
        fullfile('models', 'lesion_detection'), ...
        fullfile('models', 'train'), ...
        fullfile('models', 'inference'), ...
        fullfile('models', 'saved'), ...
        'explainability', ...
        'evaluation', ...
        'inference' ...
    };

    addpath(matlabDir);
    for i = 1:numel(subdirs)
        targetPath = fullfile(matlabDir, subdirs{i});
        if exist(targetPath, 'dir') == 7
            addpath(targetPath);
        end
    end

    % Add demo/matlab_app path
    demoAppDir = fullfile(aiEngineDir, 'demo', 'matlab_app');
    if exist(demoAppDir, 'dir') == 7
        addpath(demoAppDir);
    end

    % Add config and tests paths
    configDir = fullfile(aiEngineDir, 'config');
    testsDir = fullfile(aiEngineDir, 'tests');

    if exist(configDir, 'dir') == 7
        addpath(configDir);
    end
    if exist(testsDir, 'dir') == 7
        addpath(testsDir);
    end

    fprintf('[Retino-AI] Workspace paths initialized successfully.\n');
    fprintf('[Retino-AI] Root directory: %s\n', aiEngineDir);
end
