function report = verify_environment()
% VERIFY_ENVIRONMENT Checks MATLAB toolboxes and project directory structure
% Project: SIH26038 - Explainable AI for Diabetic Retinopathy Screening in Rural India
%
% Usage:
%   report = verify_environment();

    fprintf('=================================================================\n');
    fprintf('  Retino-AI Engine: Environment & Health Verification\n');
    fprintf('  SIH26038 - Explainable AI for Diabetic Retinopathy Screening\n');
    fprintf('=================================================================\n\n');

    % 1. MATLAB Version Check
    v = ver('MATLAB');
    if ~isempty(v)
        fprintf('[SYSTEM] MATLAB Version: %s (%s)\n', v.Version, v.Release);
    else
        fprintf('[SYSTEM] MATLAB Version: Unknown\n');
    end

    % 2. Required & Optional Toolboxes
    requiredToolboxes = {
        'Image Processing Toolbox', ...
        'Computer Vision Toolbox', ...
        'Statistics and Machine Learning Toolbox', ...
        'Medical Imaging Toolbox'
    };

    optionalToolboxes = {
        'Deep Learning Toolbox'
    };

    allToolboxes = ver;
    installedNames = {allToolboxes.Name};

    fprintf('\n--- Checking Required Toolboxes ---\n');
    missingRequired = 0;
    for i = 1:numel(requiredToolboxes)
        tb = requiredToolboxes{i};
        if any(strcmpi(installedNames, tb))
            fprintf('  [PASS] %s is installed.\n', tb);
        else
            fprintf('  [FAIL] %s is MISSING (Required for Retino-AI).\n', tb);
            missingRequired = missingRequired + 1;
        end
    end

    fprintf('\n--- Checking Optional Toolboxes ---\n');
    missingOptional = 0;
    for i = 1:numel(optionalToolboxes)
        tb = optionalToolboxes{i};
        if any(strcmpi(installedNames, tb))
            fprintf('  [PASS] %s is installed (Optional future dependency).\n', tb);
        else
            fprintf('  [INFO] %s is not installed (Optional; reserved for future phases).\n', tb);
            missingOptional = missingOptional + 1;
        end
    end

    % 3. Project Directory Structure Check
    testDir = fileparts(mfilename('fullpath'));
    rootDir = fileparts(testDir);

    expectedDirs = { ...
        fullfile('data', 'raw', 'aptos'), ...
        fullfile('data', 'raw', 'idrid'), ...
        fullfile('data', 'raw', 'drive'), ...
        fullfile('data', 'raw', 'messidor2'), ...
        fullfile('data', 'processed', 'aptos'), ...
        fullfile('data', 'processed', 'idrid'), ...
        fullfile('data', 'processed', 'drive'), ...
        fullfile('data', 'processed', 'messidor2'), ...
        fullfile('data', 'splits', 'aptos'), ...
        fullfile('data', 'splits', 'idrid'), ...
        fullfile('data', 'splits', 'drive'), ...
        fullfile('data', 'splits', 'messidor2'), ...
        fullfile('matlab', 'data', 'aptos'), ...
        fullfile('matlab', 'data', 'idrid'), ...
        fullfile('matlab', 'data', 'drive'), ...
        fullfile('matlab', 'data', 'messidor2'), ...
        fullfile('matlab', 'preprocessing'), ...
        fullfile('matlab', 'quality_assessment'), ...
        fullfile('matlab', 'feature_extraction'), ...
        fullfile('matlab', 'models', 'classification'), ...
        fullfile('matlab', 'models', 'vessel_segmentation'), ...
        fullfile('matlab', 'models', 'lesion_detection'), ...
        fullfile('matlab', 'models', 'train'), ...
        fullfile('matlab', 'models', 'inference'), ...
        fullfile('matlab', 'models', 'saved'), ...
        fullfile('matlab', 'explainability'), ...
        fullfile('matlab', 'evaluation'), ...
        fullfile('matlab', 'inference'), ...
        fullfile('python', 'utils'), ...
        fullfile('python', 'integration'), ...
        fullfile('demo', 'matlab_app'), ...
        fullfile('outputs', 'preprocessing'), ...
        fullfile('outputs', 'quality'), ...
        fullfile('outputs', 'features'), ...
        fullfile('outputs', 'models'), ...
        fullfile('outputs', 'evaluation'), ...
        fullfile('outputs', 'evidence'), ...
        fullfile('outputs', 'demo'), ...
        'config', ...
        'tests', ...
        'sample_data', ...
        'outputs', ...
        'docs' ...
    };

    fprintf('\n--- Checking Workspace Directories ---\n');
    missingDirs = 0;
    for i = 1:numel(expectedDirs)
        dirRel = expectedDirs{i};
        dirFull = fullfile(rootDir, dirRel);
        if exist(dirFull, 'dir') == 7
            fprintf('  [PASS] %s\n', dirRel);
        else
            fprintf('  [FAIL] Missing directory: %s\n', dirRel);
            missingDirs = missingDirs + 1;
        end
    end

    % 4. Summary Verdict
    fprintf('\n=================================================================\n');
    if missingRequired == 0 && missingDirs == 0
        fprintf('  STATUS: ALL CHECKS PASSED. AI Engine workspace is healthy.\n');
        isHealthy = true;
    else
        fprintf('  STATUS: ACTION NEEDED (%d missing required toolbox(es), %d missing dir(s))\n', ...
            missingRequired, missingDirs);
        isHealthy = false;
    end
    fprintf('=================================================================\n\n');

    if nargout > 0
        report.isHealthy = isHealthy;
        report.missingRequired = missingRequired;
        report.missingOptional = missingOptional;
        report.missingDirs = missingDirs;
    end
end
